export interface ROPAActivity {
  id: string;
  name: string;
  department: string;
  purpose: string;
  frequency: string;
  processOwner: string;
  dataSubjectCategories: string[];
  dataCategories: string[];
  specialCategories: string[];
  systems: string[];
  vendors: string[];
  transferDestinations: string[];
  legalBasis: string;
  consentNeeded: boolean;
  legitimateInterest?: string;
  dataSubjectRights: string[];
  retentionPeriod: string;
  disposalMethod: string;
  technicalControls: string[];
  organizationalControls: string[];
  riskScore: number;
  riskCategory: 'High' | 'Medium' | 'Low';
  mitigationSummary: string;
  lastReviewed: string;
  status: 'Healthy' | 'Needs Review' | 'Missing Data';
  isAutoGenerated: boolean;
  createdAt: string;
  linkedGAPControls?: string[];
  linkedDPIAs?: string[];
  linkedTIAs?: string[];
}

export interface ROPAHealthMetrics {
  missingLawfulBasis: number;
  missingRetention: number;
  missingSystemMapping: number;
  outdatedActivities: number;
}

