'use client'

import { useState, useEffect } from 'react';
import {
  Box,
  Button,
  Checkbox,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  FormControlLabel,
  IconButton,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import { ROPAActivity } from './ropaTypes';

interface ROPAAddEditModalProps {
  open: boolean;
  onClose: () => void;
  activity?: ROPAActivity | null;
}

const departments = ['HR', 'Sales', 'Marketing', 'Finance', 'IT', 'Procurement', 'Legal'];
const dataSubjectCategories = ['Employees', 'Customers', 'Vendors', 'Prospects', 'Website Visitors', 'Contractors'];
const dataCategories = [
  'Personal Identifiers',
  'Contact Information',
  'Financial Data',
  'Behavioral Data',
  'Device Information',
  'Location Data',
  'Identity Documents',
  'Tax Information',
];
const systems = ['SAP HR', 'Payroll System', 'CRM System', 'Analytics Platform', 'Marketing Automation', 'ERP System', 'Accounting Software', 'Website', 'Vendor Portal'];
const vendors = ['ADP', 'Tax Service Provider', 'Identity Verification Provider', 'Google Analytics', 'Marketing Cloud', 'Cloud Accounting Provider', 'Cookie Consent Tool'];
const countries = ['USA', 'EU', 'India', 'UK', 'Canada', 'Australia'];
const legalBasisOptions = ['Consent', 'Contract', 'Legal Obligation', 'Vital Interests', 'Public Task', 'Legitimate Interest'];
const retentionPeriods = ['1 year', '2 years', '5 years', '7 years', '10 years', 'Indefinite'];
const riskLevels = ['Low', 'Medium', 'High'];

export default function ROPAAddEditModal({ open, onClose, activity }: ROPAAddEditModalProps) {
  const isEdit = !!activity;
  const [formData, setFormData] = useState({
    name: '',
    department: '',
    purpose: '',
    frequency: '',
    processOwner: '',
    dataSubjectCategories: [] as string[],
    dataCategories: [] as string[],
    systems: [] as string[],
    vendors: [] as string[],
    transferDestinations: [] as string[],
    legalBasis: '',
    consentNeeded: false,
    legitimateInterest: '',
    retentionPeriod: '',
    riskLevel: 'Medium',
    isAutoGenerated: false,
  });

  useEffect(() => {
    if (activity) {
      setFormData({
        name: activity.name,
        department: activity.department,
        purpose: activity.purpose,
        frequency: activity.frequency,
        processOwner: activity.processOwner,
        dataSubjectCategories: activity.dataSubjectCategories,
        dataCategories: activity.dataCategories,
        systems: activity.systems,
        vendors: activity.vendors,
        transferDestinations: activity.transferDestinations,
        legalBasis: activity.legalBasis,
        consentNeeded: activity.consentNeeded,
        legitimateInterest: activity.legitimateInterest || '',
        retentionPeriod: activity.retentionPeriod,
        riskLevel: activity.riskCategory,
        isAutoGenerated: activity.isAutoGenerated,
      });
    } else {
      setFormData({
        name: '',
        department: '',
        purpose: '',
        frequency: '',
        processOwner: '',
        dataSubjectCategories: [],
        dataCategories: [],
        systems: [],
        vendors: [],
        transferDestinations: [],
        legalBasis: '',
        consentNeeded: false,
        legitimateInterest: '',
        retentionPeriod: '',
        riskLevel: 'Medium',
        isAutoGenerated: false,
      });
    }
  }, [activity, open]);

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleMultiSelectChange = (field: string, value: string[]) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleSave = () => {
    // In a real app, this would save to backend
    // For now, just close the modal
    console.log('Saving ROPA activity:', formData);
    onClose();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth PaperProps={{ sx: { maxHeight: '90vh' } }}>
      <DialogTitle>
        <Stack direction="row" justifyContent="space-between" alignItems="center">
          <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px' }}>
            {isEdit ? 'Edit Processing Activity' : 'Add Processing Activity'}
          </Typography>
          <IconButton onClick={onClose} size="small">
            <CloseIcon />
          </IconButton>
        </Stack>
      </DialogTitle>
      <DialogContent dividers>
        <Stack spacing={2} sx={{ pt: 1 }}>
          {/* Agentic Placeholder */}
          {!isEdit && formData.name && (
            <Box
              sx={{
                p: 1.5,
                backgroundColor: 'info.light',
                border: '1px solid',
                borderColor: 'info.main',
                borderRadius: '8px',
              }}
            >
              <Typography variant="caption" sx={{ fontSize: '12px', color: 'text.primary' }}>
                💡 Kaitaki will pre-fill recommended fields automatically in a future version.
              </Typography>
            </Box>
          )}

          {/* Basic Information */}
          <TextField
            label="Activity Name"
            value={formData.name}
            onChange={(e) => handleChange('name', e.target.value)}
            fullWidth
            required
            size="small"
            placeholder="e.g., Payroll Processing"
          />

          <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
            <FormControl fullWidth size="small" required>
              <InputLabel>Department</InputLabel>
              <Select
                value={formData.department}
                label="Department"
                onChange={(e) => handleChange('department', e.target.value)}
              >
                {departments.map((dept) => (
                  <MenuItem key={dept} value={dept}>
                    {dept}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            <TextField
              label="Frequency"
              value={formData.frequency}
              onChange={(e) => handleChange('frequency', e.target.value)}
              fullWidth
              size="small"
              placeholder="e.g., Monthly, Daily, Continuous"
            />
          </Stack>

          <TextField
            label="Description/Purpose"
            value={formData.purpose}
            onChange={(e) => handleChange('purpose', e.target.value)}
            fullWidth
            multiline
            rows={3}
            required
            size="small"
            placeholder="Describe the purpose of this processing activity..."
          />

          <TextField
            label="Process Owner"
            value={formData.processOwner}
            onChange={(e) => handleChange('processOwner', e.target.value)}
            fullWidth
            size="small"
            placeholder="Name of the process owner"
          />

          {/* Data Categories */}
          <FormControl fullWidth size="small">
            <InputLabel>Data Subject Categories</InputLabel>
            <Select
              multiple
              value={formData.dataSubjectCategories}
              label="Data Subject Categories"
              onChange={(e) => handleMultiSelectChange('dataSubjectCategories', e.target.value as string[])}
              renderValue={(selected) => (selected as string[]).join(', ')}
            >
              {dataSubjectCategories.map((cat) => (
                <MenuItem key={cat} value={cat}>
                  <Checkbox checked={formData.dataSubjectCategories.indexOf(cat) > -1} />
                  {cat}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth size="small">
            <InputLabel>Data Categories</InputLabel>
            <Select
              multiple
              value={formData.dataCategories}
              label="Data Categories"
              onChange={(e) => handleMultiSelectChange('dataCategories', e.target.value as string[])}
              renderValue={(selected) => (selected as string[]).join(', ')}
            >
              {dataCategories.map((cat) => (
                <MenuItem key={cat} value={cat}>
                  <Checkbox checked={formData.dataCategories.indexOf(cat) > -1} />
                  {cat}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          {/* Systems & Vendors */}
          <FormControl fullWidth size="small">
            <InputLabel>Systems</InputLabel>
            <Select
              multiple
              value={formData.systems}
              label="Systems"
              onChange={(e) => handleMultiSelectChange('systems', e.target.value as string[])}
              renderValue={(selected) => (selected as string[]).join(', ')}
            >
              {systems.map((sys) => (
                <MenuItem key={sys} value={sys}>
                  <Checkbox checked={formData.systems.indexOf(sys) > -1} />
                  {sys}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth size="small">
            <InputLabel>Vendors/Processors</InputLabel>
            <Select
              multiple
              value={formData.vendors}
              label="Vendors/Processors"
              onChange={(e) => handleMultiSelectChange('vendors', e.target.value as string[])}
              renderValue={(selected) => (selected as string[]).join(', ')}
            >
              {vendors.map((vendor) => (
                <MenuItem key={vendor} value={vendor}>
                  <Checkbox checked={formData.vendors.indexOf(vendor) > -1} />
                  {vendor}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth size="small">
            <InputLabel>Transfer Destinations (Countries)</InputLabel>
            <Select
              multiple
              value={formData.transferDestinations}
              label="Transfer Destinations (Countries)"
              onChange={(e) => handleMultiSelectChange('transferDestinations', e.target.value as string[])}
              renderValue={(selected) => (selected as string[]).join(', ')}
            >
              {countries.map((country) => (
                <MenuItem key={country} value={country}>
                  <Checkbox checked={formData.transferDestinations.indexOf(country) > -1} />
                  {country}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          {/* Legal Basis */}
          <FormControl fullWidth size="small" required>
            <InputLabel>Legal Basis</InputLabel>
            <Select
              value={formData.legalBasis}
              label="Legal Basis"
              onChange={(e) => handleChange('legalBasis', e.target.value)}
            >
              {legalBasisOptions.map((basis) => (
                <MenuItem key={basis} value={basis}>
                  {basis}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControlLabel
            control={
              <Checkbox
                checked={formData.consentNeeded}
                onChange={(e) => handleChange('consentNeeded', e.target.checked)}
              />
            }
            label="Consent Needed"
          />

          {formData.legalBasis === 'Legitimate Interest' && (
            <TextField
              label="Legitimate Interest Description"
              value={formData.legitimateInterest}
              onChange={(e) => handleChange('legitimateInterest', e.target.value)}
              fullWidth
              multiline
              rows={2}
              size="small"
              placeholder="Describe the legitimate interest..."
            />
          )}

          {/* Retention & Risk */}
          <FormControl fullWidth size="small">
            <InputLabel>Retention Period</InputLabel>
            <Select
              value={formData.retentionPeriod}
              label="Retention Period"
              onChange={(e) => handleChange('retentionPeriod', e.target.value)}
            >
              {retentionPeriods.map((period) => (
                <MenuItem key={period} value={period}>
                  {period}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth size="small">
            <InputLabel>Risk Level</InputLabel>
            <Select
              value={formData.riskLevel}
              label="Risk Level"
              onChange={(e) => handleChange('riskLevel', e.target.value)}
            >
              {riskLevels.map((level) => (
                <MenuItem key={level} value={level}>
                  {level}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          {/* Auto-generated Toggle */}
          <FormControlLabel
            control={
              <Checkbox
                checked={formData.isAutoGenerated}
                onChange={(e) => handleChange('isAutoGenerated', e.target.checked)}
              />
            }
            label="Mark as auto-generated (for demo purposes)"
          />
        </Stack>
      </DialogContent>
      <DialogActions sx={{ p: 2 }}>
        <Button onClick={onClose} sx={{ textTransform: 'none' }}>
          Cancel
        </Button>
        <Button onClick={handleSave} variant="contained" sx={{ textTransform: 'none' }}>
          Save
        </Button>
      </DialogActions>
    </Dialog>
  );
}

