'use client'

import { useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  Box,
  Button,
  Chip,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tooltip,
  Typography,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { ROPAActivity } from './ropaTypes';
import { mockROPAActivities } from './ropaData';

interface ROPATableProps {
  onEditActivity: (activity: ROPAActivity) => void;
  onAddActivity: () => void;
}

const getRiskColor = (risk: string): 'success' | 'warning' | 'error' | 'default' => {
  switch (risk) {
    case 'Low':
      return 'success';
    case 'Medium':
      return 'warning';
    case 'High':
      return 'error';
    default:
      return 'default';
  }
};

const getStatusColor = (status: string): 'success' | 'warning' | 'error' | 'default' => {
  switch (status) {
    case 'Healthy':
      return 'success';
    case 'Needs Review':
      return 'warning';
    case 'Missing Data':
      return 'error';
    default:
      return 'default';
  }
};

const getCountryFlag = (country: string): string => {
  const flags: Record<string, string> = {
    USA: '🇺🇸',
    EU: '🇪🇺',
    UK: '🇬🇧',
    India: '🇮🇳',
    Canada: '🇨🇦',
    Australia: '🇦🇺',
  };
  return flags[country] || '🌍';
};

export default function ROPATable({ onEditActivity, onAddActivity }: ROPATableProps) {
  const router = useRouter();

  const handleRowClick = (activityId: string) => {
    router.push(`/ropa/${activityId}`);
  };

  return (
    <Box>
      <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '16px' }}>
          Processing Activities Register
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={onAddActivity}
          size="small"
          sx={{ textTransform: 'none' }}
        >
          Add Processing Activity
        </Button>
      </Stack>

      <TableContainer component={Paper} variant="outlined" sx={{ width: '100%' }}>
        <Table sx={{ width: '100%' }} size="small">
          <TableHead>
            <TableRow sx={{ backgroundColor: 'grey.50' }}>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Activity Name</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Department</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Purpose</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Lawful Basis</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Systems</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Vendors</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Transfers</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Retention</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Risk Level</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Last Reviewed</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Reviewed By</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Status</TableCell>
              <TableCell sx={{ fontWeight: 600, fontSize: '12px' }}>Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {mockROPAActivities.map((activity) => (
              <TableRow
                key={activity.id}
                hover
                onClick={() => handleRowClick(activity.id)}
                sx={{
                  cursor: 'pointer',
                  '&:hover': { backgroundColor: 'action.hover' },
                }}
              >
                <TableCell>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                      {activity.name}
                    </Typography>
                    {activity.isAutoGenerated && (
                      <Tooltip title="Generated using GAP + Pre-Qualification data." arrow>
                        <Chip label="Auto-Generated" size="small" sx={{ fontSize: '10px', height: 20 }} />
                      </Tooltip>
                    )}
                  </Stack>
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>{activity.department}</TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px', maxWidth: 200 }}>
                  <Typography
                    variant="body2"
                    sx={{
                      fontSize: '14px',
                      lineHeight: '20px',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    {activity.purpose}
                  </Typography>
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.legalBasis}
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.systems.length > 0 ? (
                    <Stack direction="row" spacing={0.5} flexWrap="wrap">
                      {activity.systems.slice(0, 2).map((sys) => (
                        <Chip
                          key={sys}
                          label={sys}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      ))}
                      {activity.systems.length > 2 && (
                        <Chip
                          label={`+${activity.systems.length - 2}`}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      )}
                    </Stack>
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.vendors.length > 0 ? (
                    <Stack direction="row" spacing={0.5} flexWrap="wrap">
                      {activity.vendors.slice(0, 2).map((vendor) => (
                        <Chip
                          key={vendor}
                          label={vendor}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      ))}
                      {activity.vendors.length > 2 && (
                        <Chip
                          label={`+${activity.vendors.length - 2}`}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      )}
                    </Stack>
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.transferDestinations.length > 0 ? (
                    <Stack direction="row" spacing={0.5} flexWrap="wrap">
                      {activity.transferDestinations.slice(0, 2).map((dest) => (
                        <Chip
                          key={dest}
                          label={`${getCountryFlag(dest)} ${dest}`}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      ))}
                      {activity.transferDestinations.length > 2 && (
                        <Chip
                          label={`+${activity.transferDestinations.length - 2}`}
                          size="small"
                          variant="outlined"
                          sx={{ fontSize: '10px', height: 20, backgroundColor: 'grey.50' }}
                        />
                      )}
                    </Stack>
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.retentionPeriod || (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      Not set
                    </Typography>
                  )}
                </TableCell>
                <TableCell>
                  <Chip
                    label={activity.riskCategory}
                    size="small"
                    color={getRiskColor(activity.riskCategory)}
                    sx={{ fontSize: '11px', height: 22 }}
                  />
                </TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>{activity.lastReviewed}</TableCell>
                <TableCell sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.processOwner || 'Privacy Champion'}
                </TableCell>
                <TableCell>
                  <Chip
                    label={activity.status}
                    size="small"
                    color={getStatusColor(activity.status)}
                    sx={{
                      fontSize: '11px',
                      height: 22,
                      ...(activity.status === 'Missing Data' && {
                        backgroundColor: '#FF6B35',
                        color: 'white',
                        '&:hover': { backgroundColor: '#E55A2B' },
                      }),
                    }}
                  />
                </TableCell>
                <TableCell
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                  }}
                  sx={{ position: 'relative', zIndex: 1 }}
                >
                  <Stack direction="row" spacing={0.5}>
                    <Button
                      size="small"
                      component={Link}
                      href={`/ropa/${activity.id}`}
                      onClick={(e) => e.stopPropagation()}
                      sx={{ fontSize: '12px', minWidth: 'auto', px: 1 }}
                    >
                      View
                    </Button>
                    <Button
                      size="small"
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        onEditActivity(activity);
                      }}
                      sx={{ fontSize: '12px', minWidth: 'auto', px: 1 }}
                    >
                      Edit
                    </Button>
                  </Stack>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );
}

