'use client'

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Divider,
  Stack,
  Typography,
} from '@mui/material';
import EditIcon from '@mui/icons-material/Edit';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { mockROPAActivities } from './ropaData';
import { ROPAActivity } from './ropaTypes';
import ROPADataFlowMap from './ROPADataFlowMap';
import AssessmentSetupWizard from './AssessmentSetupWizard';

interface ROPADetailPageProps {
  activityId: string;
}

export default function ROPADetailPage({ activityId }: ROPADetailPageProps) {
  const router = useRouter();
  const [wizardOpen, setWizardOpen] = useState(false);
  const [wizardData, setWizardData] = useState<{ type: string; reason: string } | null>(null);

  const activity = useMemo(() => {
    return mockROPAActivities.find((a) => a.id === activityId);
  }, [activityId]);

  if (!activity) {
    return (
      <Box sx={{ p: 4, textAlign: 'center' }}>
        <Typography variant="h6" sx={{ color: 'text.secondary' }}>
          Activity not found
        </Typography>
        <Button onClick={() => router.push('/ropa')} sx={{ mt: 2 }}>
          Back to ROPA
        </Button>
      </Box>
    );
  }

  const handleStartAssessment = (assessmentType: string, reason: string) => {
    setWizardData({ type: assessmentType, reason });
    setWizardOpen(true);
  };

  const handleCloseWizard = () => {
    setWizardOpen(false);
    setWizardData(null);
  };

  const getRiskColor = (risk: string): 'success' | 'warning' | 'error' => {
    switch (risk) {
      case 'Low':
        return 'success';
      case 'Medium':
        return 'warning';
      case 'High':
        return 'error';
      default:
        return 'warning';
    }
  };

  const getStatusColor = (status: string): 'success' | 'warning' | 'error' => {
    switch (status) {
      case 'Healthy':
        return 'success';
      case 'Needs Review':
        return 'warning';
      case 'Missing Data':
        return 'error';
      default:
        return 'warning';
    }
  };

  return (
    <Box sx={{ width: '100%', maxWidth: '100%', minWidth: 0, px: 4, py: 3 }}>
      <Stack spacing={4}>
        {/* Header */}
        <Box>
          <Button
            startIcon={<ArrowBackIcon />}
            onClick={() => router.push('/ropa')}
            sx={{ mb: 2, textTransform: 'none' }}
          >
            Back to ROPA
          </Button>
          <Stack direction="row" justifyContent="space-between" alignItems="flex-start" sx={{ mb: 2 }}>
            <Box sx={{ flex: 1 }}>
              <Stack direction="row" spacing={1.5} alignItems="center" flexWrap="wrap" sx={{ mb: 1 }}>
                <Typography variant="h4" sx={{ fontWeight: 600, fontSize: '24px' }}>
                  {activity.name}
                </Typography>
                <Chip
                  label={activity.status}
                  size="small"
                  color={getStatusColor(activity.status)}
                  sx={{ fontSize: '12px', height: 24 }}
                />
                <Chip
                  label={activity.riskCategory}
                  size="small"
                  color={getRiskColor(activity.riskCategory)}
                  sx={{ fontSize: '12px', height: 24 }}
                />
                {activity.isAutoGenerated && (
                  <Chip label="Auto-Generated" size="small" sx={{ fontSize: '11px', height: 22 }} />
                )}
              </Stack>
              <Stack direction="row" spacing={3} flexWrap="wrap">
                <Typography variant="body2" sx={{ color: 'text.secondary', fontSize: '14px' }}>
                  <strong>Department:</strong> {activity.department}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary', fontSize: '14px' }}>
                  <strong>Last Reviewed:</strong> {activity.lastReviewed}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary', fontSize: '14px' }}>
                  <strong>Owner:</strong> {activity.processOwner || 'Privacy Champion'}
                </Typography>
              </Stack>
            </Box>
            <Stack direction="row" spacing={1.5}>
              <Button
                variant="contained"
                onClick={() => handleStartAssessment('DPIA', 'Start assessment for this activity')}
                sx={{ textTransform: 'none' }}
              >
                Start Assessment
              </Button>
              <Button variant="outlined" startIcon={<EditIcon />} sx={{ textTransform: 'none' }}>
                Edit Activity
              </Button>
            </Stack>
          </Stack>
        </Box>

        {/* Agent Suggestion Placeholder */}
        {activity.status === 'Missing Data' && (
          <Box
            sx={{
              p: 1.5,
              backgroundColor: 'warning.light',
              border: '1px solid',
              borderColor: 'warning.main',
              borderRadius: '8px',
            }}
          >
            <Typography variant="caption" sx={{ fontSize: '12px', color: 'text.primary' }}>
              💡 <strong>Agent Suggestion:</strong> This activity is missing retention details.
            </Typography>
          </Box>
        )}

        {/* Section 1: Basic Information */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Basic Information
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Purpose
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.purpose}
                </Typography>
              </Box>
              <Stack direction={{ xs: 'column', sm: 'row' }} spacing={3}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                    Frequency
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                    {activity.frequency}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                    Process Owner
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                    {activity.processOwner}
                  </Typography>
                </Box>
              </Stack>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 2: Data Flow Visual Map */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Data Flow Visual Map
            </Typography>
            <ROPADataFlowMap activity={activity} />
          </CardContent>
        </Card>

        {/* Section 3: Personal Data */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Personal Data
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Data Subject Categories
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.dataSubjectCategories.map((cat) => (
                    <Chip key={cat} label={cat} size="small" sx={{ fontSize: '12px', height: 24 }} />
                  ))}
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Data Categories
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.dataCategories.map((cat) => (
                    <Chip key={cat} label={cat} size="small" sx={{ fontSize: '12px', height: 24 }} />
                  ))}
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Special Categories
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.specialCategories.join(', ') || 'None'}
                </Typography>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 4: Systems & Vendors */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Systems & Vendors
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Systems Involved
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.systems.length > 0 ? (
                    activity.systems.map((sys) => (
                      <Chip key={sys} label={sys} size="small" variant="outlined" sx={{ fontSize: '12px', height: 24 }} />
                    ))
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Vendors/Processors
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.vendors.length > 0 ? (
                    activity.vendors.map((vendor) => (
                      <Chip key={vendor} label={vendor} size="small" variant="outlined" sx={{ fontSize: '12px', height: 24 }} />
                    ))
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Transfer Destinations
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.transferDestinations.length > 0 ? (
                    activity.transferDestinations.map((dest) => (
                      <Chip
                        key={dest}
                        label={`${getCountryFlag(dest)} ${dest}`}
                        size="small"
                        variant="outlined"
                        sx={{ fontSize: '12px', height: 24 }}
                      />
                    ))
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </Stack>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 5: Legal Basis & Rights */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Legal Basis & Rights
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Legal Basis
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.legalBasis}
                </Typography>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Consent Needed
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.consentNeeded ? 'Yes' : 'No'}
                </Typography>
              </Box>
              {activity.legitimateInterest && (
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                    Legitimate Interest
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                    {activity.legitimateInterest}
                  </Typography>
                </Box>
              )}
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Data Subject Rights Impact
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.dataSubjectRights.map((right) => (
                    <Chip key={right} label={right} size="small" sx={{ fontSize: '12px', height: 24 }} />
                  ))}
                </Stack>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 6: Retention */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Retention
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Retention Period
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.retentionPeriod || 'Not specified'}
                </Typography>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Disposal Method
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.disposalMethod || 'Not specified'}
                </Typography>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 7: Security Measures */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Security Measures
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Technical Controls
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.technicalControls.length > 0 ? (
                    activity.technicalControls.map((control) => (
                      <Chip key={control} label={control} size="small" sx={{ fontSize: '12px', height: 24 }} />
                    ))
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                  Organizational Controls
                </Typography>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {activity.organizationalControls.length > 0 ? (
                    activity.organizationalControls.map((control) => (
                      <Chip key={control} label={control} size="small" sx={{ fontSize: '12px', height: 24 }} />
                    ))
                  ) : (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      None
                    </Typography>
                  )}
                </Stack>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 8: Risks */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Risks
            </Typography>
            <Stack spacing={2}>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Risk Score
                </Typography>
                <Stack direction="row" spacing={1} alignItems="center">
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                    {activity.riskScore}
                  </Typography>
                  <Chip
                    label={activity.riskCategory}
                    size="small"
                    color={getRiskColor(activity.riskCategory)}
                    sx={{ fontSize: '12px', height: 24 }}
                  />
                </Stack>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 0.5 }}>
                  Mitigation Summary
                </Typography>
                <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                  {activity.mitigationSummary || 'Not specified'}
                </Typography>
              </Box>
            </Stack>
          </CardContent>
        </Card>

        {/* Section 9: Linked Assessments */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Linked Assessments
            </Typography>
            <Stack spacing={2}>
              {activity.linkedGAPControls && activity.linkedGAPControls.length > 0 && (
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                    GAP Controls
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap">
                    {activity.linkedGAPControls.map((control) => (
                      <Chip key={control} label={control} size="small" sx={{ fontSize: '12px', height: 24 }} />
                    ))}
                  </Stack>
                </Box>
              )}
              {activity.linkedDPIAs && activity.linkedDPIAs.length > 0 && (
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', display: 'block', mb: 1 }}>
                    DPIAs
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap">
                    {activity.linkedDPIAs.map((dpia) => (
                      <Chip key={dpia} label={dpia} size="small" sx={{ fontSize: '12px', height: 24 }} />
                    ))}
                  </Stack>
                </Box>
              )}
              {(!activity.linkedGAPControls || activity.linkedGAPControls.length === 0) &&
                (!activity.linkedDPIAs || activity.linkedDPIAs.length === 0) && (
                  <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                    No linked assessments
                  </Typography>
                )}
            </Stack>
          </CardContent>
        </Card>

        {/* Section 10: Assessment Requirements */}
        <Card variant="outlined">
          <CardContent sx={{ p: 3 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px', mb: 2 }}>
              Assessment Requirements (Auto-Detected)
            </Typography>
            <Stack spacing={2}>
              {/* DPIA Required */}
              {activity.riskCategory === 'High' && (
                <Box
                  sx={{
                    p: 2,
                    border: '1px solid',
                    borderColor: 'divider',
                    borderRadius: '8px',
                    backgroundColor: 'background.paper',
                  }}
                >
                  <Stack spacing={1}>
                    <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                      • DPIA – Required
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      Reason: High-risk processing detected.
                    </Typography>
                    <Button
                      variant="contained"
                      size="small"
                      onClick={() => handleStartAssessment('DPIA', 'High-risk processing detected.')}
                      sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                    >
                      Start Assessment
                    </Button>
                  </Stack>
                </Box>
              )}

              {/* TIA Required */}
              {activity.transferDestinations.length > 0 &&
                (activity.transferDestinations.includes('USA') ||
                  activity.transferDestinations.some((d) => d !== 'EU' && d !== 'UK')) && (
                  <Box
                    sx={{
                      p: 2,
                      border: '1px solid',
                      borderColor: 'divider',
                      borderRadius: '8px',
                      backgroundColor: 'background.paper',
                    }}
                  >
                    <Stack spacing={1}>
                      <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                        • TIA – Required
                      </Typography>
                      <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                        Reason: Cross-border data transfer detected ({activity.transferDestinations.join(', ')}).
                      </Typography>
                      <Button
                        variant="contained"
                        size="small"
                        onClick={() =>
                          handleStartAssessment('TIA', `Cross-border data transfer detected (${activity.transferDestinations.join(', ')}).`)
                        }
                        sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                      >
                        Start Assessment
                      </Button>
                    </Stack>
                  </Box>
                )}

              {/* LIA Recommended */}
              {activity.legalBasis === 'Legitimate Interest' && (
                <Box
                  sx={{
                    p: 2,
                    border: '1px solid',
                    borderColor: 'divider',
                    borderRadius: '8px',
                    backgroundColor: 'background.paper',
                  }}
                >
                  <Stack spacing={1}>
                    <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                      • LIA – Recommended
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      Reason: Legitimate Interest identified.
                    </Typography>
                    <Button
                      variant="contained"
                      size="small"
                      onClick={() => handleStartAssessment('LIA', 'Legitimate Interest identified.')}
                      sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                    >
                      Start Assessment
                    </Button>
                  </Stack>
                </Box>
              )}

              {/* Vendor Risk Assessment */}
              {activity.vendors.length > 0 && activity.transferDestinations.length > 0 && (
                <Box
                  sx={{
                    p: 2,
                    border: '1px solid',
                    borderColor: 'divider',
                    borderRadius: '8px',
                    backgroundColor: 'background.paper',
                  }}
                >
                  <Stack spacing={1}>
                    <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                      • Vendor Risk Assessment – Required
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      Reason: External processor involved.
                    </Typography>
                    <Button
                      variant="contained"
                      size="small"
                      onClick={() => handleStartAssessment('Vendor Risk Assessment', 'External processor involved.')}
                      sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                    >
                      Start Assessment
                    </Button>
                  </Stack>
                </Box>
              )}

              {/* No assessments required */}
              {activity.riskCategory !== 'High' &&
                activity.transferDestinations.length === 0 &&
                activity.legalBasis !== 'Legitimate Interest' &&
                activity.vendors.length === 0 && (
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    No assessments required for this activity.
                  </Typography>
                )}
            </Stack>
          </CardContent>
        </Card>
      </Stack>

      {/* Assessment Setup Wizard */}
      {wizardData && (
        <AssessmentSetupWizard
          open={wizardOpen}
          onClose={handleCloseWizard}
          activityName={activity.name}
          assessmentType={wizardData.type}
          reason={wizardData.reason}
        />
      )}
    </Box>
  );
}

const getCountryFlag = (country: string): string => {
  const flags: Record<string, string> = {
    USA: '🇺🇸',
    EU: '🇪🇺',
    UK: '🇬🇧',
    India: '🇮🇳',
    Canada: '🇨🇦',
    Australia: '🇦🇺',
  };
  return flags[country] || '🌍';
};

