'use client'

import { useState } from 'react';
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Button,
  Chip,
  Drawer,
  IconButton,
  Stack,
  Typography,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import EditIcon from '@mui/icons-material/Edit';
import { ROPAActivity } from './ropaTypes';

interface ROPADetailDrawerProps {
  activity: ROPAActivity;
  open: boolean;
  onClose: () => void;
  onEdit: () => void;
  onStartAssessment?: (assessmentType: string, reason: string) => void;
}

export default function ROPADetailDrawer({ activity, open, onClose, onEdit, onStartAssessment }: ROPADetailDrawerProps) {
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    overview: true,
    personalData: false,
    systems: false,
    legalBasis: false,
    retention: false,
    security: false,
    risks: false,
    linked: false,
    assessments: false,
  });

  const handleSectionToggle = (section: string) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const getRiskColor = (risk: string): 'success' | 'warning' | 'error' => {
    switch (risk) {
      case 'Low':
        return 'success';
      case 'Medium':
        return 'warning';
      case 'High':
        return 'error';
      default:
        return 'warning';
    }
  };

  const getStatusColor = (status: string): 'success' | 'warning' | 'error' => {
    switch (status) {
      case 'Healthy':
        return 'success';
      case 'Needs Review':
        return 'warning';
      case 'Missing Data':
        return 'error';
      default:
        return 'warning';
    }
  };

  return (
    <Drawer anchor="right" open={open} onClose={onClose} PaperProps={{ sx: { width: { xs: '100%', sm: 600 } } }}>
      <Box sx={{ p: 3, height: '100%', overflow: 'auto' }}>
        {/* Header */}
        <Stack direction="row" justifyContent="space-between" alignItems="flex-start" sx={{ mb: 3 }}>
          <Box sx={{ flex: 1 }}>
            <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}>
              <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '18px' }}>
                {activity.name}
              </Typography>
              <Chip
                label={activity.status}
                size="small"
                color={getStatusColor(activity.status)}
                sx={{ fontSize: '11px', height: 22 }}
              />
              {activity.isAutoGenerated && (
                <Chip label="Auto-Generated" size="small" sx={{ fontSize: '10px', height: 20 }} />
              )}
            </Stack>
            <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
              Last Reviewed: {activity.lastReviewed}
            </Typography>
          </Box>
          <IconButton onClick={onClose} size="small">
            <CloseIcon />
          </IconButton>
        </Stack>

        {/* Agent Suggestion Placeholder */}
        {activity.status === 'Missing Data' && (
          <Box
            sx={{
              p: 1.5,
              mb: 2,
              backgroundColor: 'warning.light',
              border: '1px solid',
              borderColor: 'warning.main',
              borderRadius: '8px',
            }}
          >
            <Typography variant="caption" sx={{ fontSize: '12px', color: 'text.primary' }}>
              💡 <strong>Agent Suggestion:</strong> This activity is missing retention information.
            </Typography>
          </Box>
        )}

        {/* Sections */}
        <Stack spacing={1}>
          {/* Overview */}
          <Accordion
            expanded={expandedSections.overview}
            onChange={() => handleSectionToggle('overview')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Overview
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Purpose
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.purpose}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Department
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.department}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Frequency
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.frequency}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Process Owner
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.processOwner}
                  </Typography>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Personal Data */}
          <Accordion
            expanded={expandedSections.personalData}
            onChange={() => handleSectionToggle('personalData')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Personal Data
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Data Subject Categories
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.dataSubjectCategories.map((cat) => (
                      <Chip key={cat} label={cat} size="small" sx={{ fontSize: '11px', height: 22 }} />
                    ))}
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Data Categories
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.dataCategories.map((cat) => (
                      <Chip key={cat} label={cat} size="small" sx={{ fontSize: '11px', height: 22 }} />
                    ))}
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Special Categories
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.specialCategories.join(', ') || 'None'}
                  </Typography>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Systems & Vendors */}
          <Accordion
            expanded={expandedSections.systems}
            onChange={() => handleSectionToggle('systems')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Systems & Vendors
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Systems Involved
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.systems.length > 0 ? (
                      activity.systems.map((sys) => (
                        <Chip key={sys} label={sys} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))
                    ) : (
                      <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                        None
                      </Typography>
                    )}
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Vendors/Processors
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.vendors.length > 0 ? (
                      activity.vendors.map((vendor) => (
                        <Chip key={vendor} label={vendor} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))
                    ) : (
                      <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                        None
                      </Typography>
                    )}
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Transfer Destinations
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.transferDestinations.length > 0 ? (
                      activity.transferDestinations.map((dest) => (
                        <Chip key={dest} label={dest} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))
                    ) : (
                      <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                        None
                      </Typography>
                    )}
                  </Stack>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Legal Basis & Rights */}
          <Accordion
            expanded={expandedSections.legalBasis}
            onChange={() => handleSectionToggle('legalBasis')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Legal Basis & Rights
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Legal Basis
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.legalBasis}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Consent Needed
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.consentNeeded ? 'Yes' : 'No'}
                  </Typography>
                </Box>
                {activity.legitimateInterest && (
                  <Box>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      Legitimate Interest
                    </Typography>
                    <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                      {activity.legitimateInterest}
                    </Typography>
                  </Box>
                )}
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Data Subject Rights Impact
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.dataSubjectRights.map((right) => (
                      <Chip key={right} label={right} size="small" sx={{ fontSize: '11px', height: 22 }} />
                    ))}
                  </Stack>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Retention */}
          <Accordion
            expanded={expandedSections.retention}
            onChange={() => handleSectionToggle('retention')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Retention
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Retention Period
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.retentionPeriod || 'Not specified'}
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Disposal Method
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.disposalMethod || 'Not specified'}
                  </Typography>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Security Measures */}
          <Accordion
            expanded={expandedSections.security}
            onChange={() => handleSectionToggle('security')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Security Measures
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Technical Controls
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.technicalControls.length > 0 ? (
                      activity.technicalControls.map((control) => (
                        <Chip key={control} label={control} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))
                    ) : (
                      <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                        None
                      </Typography>
                    )}
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Organizational Controls
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {activity.organizationalControls.length > 0 ? (
                      activity.organizationalControls.map((control) => (
                        <Chip key={control} label={control} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))
                    ) : (
                      <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                        None
                      </Typography>
                    )}
                  </Stack>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Risks */}
          <Accordion
            expanded={expandedSections.risks}
            onChange={() => handleSectionToggle('risks')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Risks
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Risk Score
                  </Typography>
                  <Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 0.5 }}>
                    <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px' }}>
                      {activity.riskScore}
                    </Typography>
                    <Chip
                      label={activity.riskCategory}
                      size="small"
                      color={getRiskColor(activity.riskCategory)}
                      sx={{ fontSize: '11px', height: 22 }}
                    />
                  </Stack>
                </Box>
                <Box>
                  <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                    Mitigation Summary
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: '14px', lineHeight: '20px', mt: 0.5 }}>
                    {activity.mitigationSummary || 'Not specified'}
                  </Typography>
                </Box>
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Linked Assessments */}
          <Accordion
            expanded={expandedSections.linked}
            onChange={() => handleSectionToggle('linked')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Linked Assessments
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={1.5}>
                {activity.linkedGAPControls && activity.linkedGAPControls.length > 0 && (
                  <Box>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      GAP Controls
                    </Typography>
                    <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                      {activity.linkedGAPControls.map((control) => (
                        <Chip key={control} label={control} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))}
                    </Stack>
                  </Box>
                )}
                {activity.linkedDPIAs && activity.linkedDPIAs.length > 0 && (
                  <Box>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      DPIAs
                    </Typography>
                    <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                      {activity.linkedDPIAs.map((dpia) => (
                        <Chip key={dpia} label={dpia} size="small" sx={{ fontSize: '11px', height: 22 }} />
                      ))}
                    </Stack>
                  </Box>
                )}
                {(!activity.linkedGAPControls || activity.linkedGAPControls.length === 0) &&
                  (!activity.linkedDPIAs || activity.linkedDPIAs.length === 0) && (
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      No linked assessments
                    </Typography>
                  )}
              </Stack>
            </AccordionDetails>
          </Accordion>

          {/* Assessment Requirements */}
          <Accordion
            expanded={expandedSections.assessments}
            onChange={() => handleSectionToggle('assessments')}
            sx={{ boxShadow: 'none', border: '1px solid', borderColor: 'divider' }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                Assessment Requirements (Auto-Detected)
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Stack spacing={2}>
                {/* DPIA Required */}
                {activity.riskCategory === 'High' && (
                  <Box
                    sx={{
                      p: 2,
                      border: '1px solid',
                      borderColor: 'divider',
                      borderRadius: '8px',
                      backgroundColor: 'background.paper',
                    }}
                  >
                    <Stack spacing={1}>
                      <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                        • DPIA – Required
                      </Typography>
                      <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                        Reason: High-risk processing detected.
                      </Typography>
                      {onStartAssessment && (
                        <Button
                          variant="contained"
                          size="small"
                          onClick={() => onStartAssessment('DPIA', 'High-risk processing detected.')}
                          sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                        >
                          Start Assessment
                        </Button>
                      )}
                    </Stack>
                  </Box>
                )}

                {/* TIA Required */}
                {activity.transferDestinations.length > 0 &&
                  (activity.transferDestinations.includes('USA') ||
                    activity.transferDestinations.some((d) => d !== 'EU' && d !== 'UK')) && (
                    <Box
                      sx={{
                        p: 2,
                        border: '1px solid',
                        borderColor: 'divider',
                        borderRadius: '8px',
                        backgroundColor: 'background.paper',
                      }}
                    >
                      <Stack spacing={1}>
                        <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                          • TIA – Required
                        </Typography>
                        <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                          Reason: Cross-border data transfer detected ({activity.transferDestinations.join(', ')}).
                        </Typography>
                        {onStartAssessment && (
                          <Button
                            variant="contained"
                            size="small"
                            onClick={() =>
                              onStartAssessment('TIA', `Cross-border data transfer detected (${activity.transferDestinations.join(', ')}).`)
                            }
                            sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                          >
                            Start Assessment
                          </Button>
                        )}
                      </Stack>
                    </Box>
                  )}

                {/* LIA Recommended */}
                {activity.legalBasis === 'Legitimate Interest' && (
                  <Box
                    sx={{
                      p: 2,
                      border: '1px solid',
                      borderColor: 'divider',
                      borderRadius: '8px',
                      backgroundColor: 'background.paper',
                    }}
                  >
                    <Stack spacing={1}>
                      <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                        • LIA – Recommended
                      </Typography>
                      <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                        Reason: Legitimate Interest identified.
                      </Typography>
                      {onStartAssessment && (
                        <Button
                          variant="contained"
                          size="small"
                          onClick={() => onStartAssessment('LIA', 'Legitimate Interest identified.')}
                          sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                        >
                          Start Assessment
                        </Button>
                      )}
                    </Stack>
                  </Box>
                )}

                {/* Vendor Risk Assessment */}
                {activity.vendors.length > 0 && activity.transferDestinations.length > 0 && (
                  <Box
                    sx={{
                      p: 2,
                      border: '1px solid',
                      borderColor: 'divider',
                      borderRadius: '8px',
                      backgroundColor: 'background.paper',
                    }}
                  >
                    <Stack spacing={1}>
                      <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '14px' }}>
                        • Vendor Risk Assessment – Required
                      </Typography>
                      <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                        Reason: External processor involved.
                      </Typography>
                      {onStartAssessment && (
                        <Button
                          variant="contained"
                          size="small"
                          onClick={() => onStartAssessment('Vendor Risk Assessment', 'External processor involved.')}
                          sx={{ alignSelf: 'flex-start', textTransform: 'none', mt: 0.5 }}
                        >
                          Start Assessment
                        </Button>
                      )}
                    </Stack>
                  </Box>
                )}

                {/* No assessments required */}
                {activity.riskCategory !== 'High' &&
                  activity.transferDestinations.length === 0 &&
                  activity.legalBasis !== 'Legitimate Interest' &&
                  activity.vendors.length === 0 && (
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px' }}>
                      No assessments required for this activity.
                    </Typography>
                  )}
              </Stack>
            </AccordionDetails>
          </Accordion>
        </Stack>

        {/* Edit Button */}
        <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid', borderColor: 'divider' }}>
          <Button
            variant="outlined"
            startIcon={<EditIcon />}
            onClick={onEdit}
            fullWidth
            sx={{ textTransform: 'none' }}
          >
            Edit Processing Activity
          </Button>
        </Box>
      </Box>
    </Drawer>
  );
}

